### ISSUE TITLE
bug(pipx): package spec errors in plugin branch

### ISSUE THREAD

**Issue by emvalbuena** [mmngreco/takt#6]
```
(base) ** takt % pipx install .
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [47 lines of output]
      configuration error: `project.version` must be pep440
      DESCRIPTION:
          The version of the project as supported by :pep:`440`.
      
      GIVEN VALUE:
          "2023.11.02-5-gfdb802c"
      
      OFFENDING RULE: 'format'
      
      DEFINITION:
          {
              "type": "string",
              "format": "pep440"
          }
      Traceback (most recent call last):
        File "/Users/**/.local/pipx/shared/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/**/.local/pipx/shared/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/**/.local/pipx/shared/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/pl/7p77l78140d6hwt_9mk57rxm0000gn/T/pip-build-env-zr867d67/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/pl/7p77l78140d6hwt_9mk57rxm0000gn/T/pip-build-env-zr867d67/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/pl/7p77l78140d6hwt_9mk57rxm0000gn/T/pip-build-env-zr867d67/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/private/var/folders/pl/7p77l78140d6hwt_9mk57rxm0000gn/T/pip-build-env-zr867d67/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/pl/7p77l78140d6hwt_9mk57rxm0000gn/T/pip-build-env-zr867d67/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 159, in setup
          dist.parse_config_files()
        File "/private/var/folders/pl/7p77l78140d6hwt_9mk57rxm0000gn/T/pip-build-env-zr867d67/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 627, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/private/var/folders/pl/7p77l78140d6hwt_9mk57rxm0000gn/T/pip-build-env-zr867d67/overlay/lib/python3.12/site-packages/setuptools/config/pyprojecttoml.py", line 66, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/pl/7p77l78140d6hwt_9mk57rxm0000gn/T/pip-build-env-zr867d67/overlay/lib/python3.12/site-packages/setuptools/config/pyprojecttoml.py", line 127, in read_configuration
          validate(subset, filepath)
        File "/private/var/folders/pl/7p77l78140d6hwt_9mk57rxm0000gn/T/pip-build-env-zr867d67/overlay/lib/python3.12/site-packages/setuptools/config/pyprojecttoml.py", line 55, in validate
          raise ValueError(f"{error}\n{summary}") from None
      ValueError: invalid pyproject.toml config: `project.version`.
      configuration error: `project.version` must be pep440
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Cannot determine package name from spec '/Users/**/Documents/git/takt'.
Check package spec for errors.
```

**Comment by asdf8601** [comment]
Ups,thank you for reporting this. I thought that version was pep440 compliant but I didn't check it. I need to find an easy way to build this strings based on git commits.

**Comment by asdf8601** [comment]
@KikeM could you please check if it works now?

**Comment by emvalbuena** [comment]
```
(base) ** takt % pipx install .
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/Users/**/.local/pipx/shared/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/**/.local/pipx/shared/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/**/.local/pipx/shared/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/pl/7p77l78140d6hwt_9mk57rxm0000gn/T/pip-build-env-k7qi0bdt/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/pl/7p77l78140d6hwt_9mk57rxm0000gn/T/pip-build-env-k7qi0bdt/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/pl/7p77l78140d6hwt_9mk57rxm0000gn/T/pip-build-env-k7qi0bdt/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/private/var/folders/pl/7p77l78140d6hwt_9mk57rxm0000gn/T/pip-build-env-k7qi0bdt/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/pl/7p77l78140d6hwt_9mk57rxm0000gn/T/pip-build-env-k7qi0bdt/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 159, in setup
          dist.parse_config_files()
        File "/private/var/folders/pl/7p77l78140d6hwt_9mk57rxm0000gn/T/pip-build-env-k7qi0bdt/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 627, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/private/var/folders/pl/7p77l78140d6hwt_9mk57rxm0000gn/T/pip-build-env-k7qi0bdt/overlay/lib/python3.12/site-packages/setuptools/config/pyprojecttoml.py", line 66, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/pl/7p77l78140d6hwt_9mk57rxm0000gn/T/pip-build-env-k7qi0bdt/overlay/lib/python3.12/site-packages/setuptools/config/pyprojecttoml.py", line 127, in read_configuration
          validate(subset, filepath)
        File "/private/var/folders/pl/7p77l78140d6hwt_9mk57rxm0000gn/T/pip-build-env-k7qi0bdt/overlay/lib/python3.12/site-packages/setuptools/config/pyprojecttoml.py", line 55, in validate
          raise ValueError(f"{error}\n{summary}") from None
      ValueError: invalid pyproject.toml config: `project`.
      configuration error: `project` must not contain {'homepage'} properties
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Cannot determine package name from spec '/Users/**/Documents/git/takt'.
Check package spec for errors.
```

I get the following error now.

**Comment by asdf8601** [comment]
I've tested it, and it seems to work now (after my last commit), so I'm closing this. Feel free to open it again if it's not fixed.
